### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by kaijieshi7** [vinbigdata-medical/MIDL2021-VinDr-RibCXR#1]
I have signed your DUA and send it to you, please reply my email.

**Comment by madexin1** [comment]
I have signed your DUA and send it to you, please reply my email.

**Comment by willywu3364** [comment]
I have signed your DUA and send it to you, please reply my email.

**Comment by madexin1** [comment]
I have received your reply ,but where is the data?&nbsp;


江月何年初照人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月27日(星期二) 下午4:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vinbigdata-medical/MIDL2021-VinDr-RibCXR] Dataset (Issue #1)





 
I have signed your DUA and send it to you, please reply my email.

**Comment by madexin1** [comment]
Hello, have you got the dataset? Can you also send me a copy? The author hasn't replied to me yet

**Comment by madexin1** [comment]
> 我已经签署了您的 DUA 并将其发送给您，请回复我的电子邮件。

Hello, have you got the dataset? Can you also send me a copy? The author hasn't replied to me yet

**Comment by levi3001** [comment]
hello, I have contacted my supervisor, please wait for him for responding

**Comment by DDZ-2020** [comment]
I have signed your DUA and send it to you, please reply my email.

**Comment by DDZ-2020** [comment]
hello, I want to ask how long I can get the downloadable link of the VinDr-RibCXR dataset.

**Comment by Amarscreed** [comment]
I have signed your DUA and send it to you, please reply my email.
